#dataset_path: /cluster/gimli/ysiddiqui/CADTextures/SingleShape/CubeTexturesForGraphQuad_gan_FC_processed
#mesh_path: /cluster/gimli/ysiddiqui/CADTextures/SingleShape-model/CubeTexturesForGraphQuad
#mesh_resolution: 128
#dataset_path: /cluster/gimli/ysiddiqui/CADTextures/SingleShape/CubeTexturePlaneQuad32_FC_processed
#mesh_path: /cluster/gimli/ysiddiqui/CADTextures/SingleShape-model/CubeTexturePlaneQuad32
#mesh_resolution: 32
#dataset_path: /cluster/gimli/ysiddiqui/CADTextures/SingleShape/CubeTexturesForGraphQuad32_FC_processed
#mesh_path: /cluster/gimli/ysiddiqui/CADTextures/SingleShape-model/CubeTexturesForGraphQuad32
#mesh_resolution: 64

dataset_path_car: ./data/CADTextures/CompCars/manifold_combined_processed
dataset_path_chair: ./data/CADTextures/Photoshape/shapenet-chairs-manifold-highres-part_processed_color
mesh_path_car: ./data/CADTextures/CompCars/manifold_combined
mesh_path_chair: ./data/CADTextures/Photoshape/shapenet-chairs-manifold-highres
# dataset_path_car: ./data/CADTextures/CompCars/manifold_combined_processed
# mesh_path_car: ./data/CADTextures/CompCars/manifold_combined
image_path_car: ./data/CADTextures/CompCars/exemplars_highres
image_path_chair: ./data/CADTextures/Photoshape/exemplars
mask_path_car: ./data/CADTextures/CompCars/exemplars_highres_mask
mask_path_chair: ./data/CADTextures/Photoshape/exemplars_mask
uv_path_car: ./data/CADTextures/CompCars/uv_map_first
uv_path_chair: ./data/CADTextures/Photoshape/uv_map
silhoutte_path_car: ./data/CADTextures/CompCars/uv_mask
silhoutte_path_chair: ./data/CADTextures/Photoshape/uv_mask
normals_path_car: ./data/CADTextures/CompCars/uv_normals
normals_path_chair: ./data/CADTextures/Photoshape/uv_normals

# [Chair]
pairmeta_path_chair: ./data/CADTextures/Photoshape-model/metadata/pairs.json
df_path_chair: ./data/CADTextures/Photoshape-model/shapenet-chairs-manifold
condition_path_chair: ./data/CADTextures/Photoshape/shapenet-chairs-manifold_autoencoder
stat_path_chair: ./data/CADTextures/Photoshape/shapenet-chairs-manifold-highres_stat.pt

experiment: fast_dev
seed: null
save_epoch: 5
sanity_steps: 1
max_epoch: 2000
scheduler: null
val_check_percent: 1.0
val_check_interval: 5
resume: null

num_mapping_layers: 5
lr_g: 0.002
lr_d: 0.001
lr_e: 0.0001
lazy_gradient_penalty_interval: 16
lazy_path_penalty_after: 0
lazy_path_penalty_interval: 4
latent_dim: 512
condition_dim: 512
lambda_gp: 1
lambda_plp: 2
lambda_patch: 1
ada_start_p: 0.  #to disable set to -1
ada_target: 0.6
ada_interval: 4
ada_fixed: False
g_channel_base: 32768
d_channel_base: 16384
d_channel_max: 512
features: normal
p_synthetic: 0.0

random_bg: grayscale
colorspace: rgb

# image_size: 256
image_size: 256
render_size: null

#progressive_switch: [10e3, 70e3, 180e3]
#alpha_switch: [5e3, 10e3, 10e3]

progressive_switch: [10e3, 40e3, 80e3, 180e3]
alpha_switch: [5e3, 10e3, 10e3, 10e3]
progressive_start_res: 6

num_patch_per_view: 4
patch_size: 64
# image_size_hres: 256
image_size_hres: 512
erode: True
camera_noise: 0.0
resume_ema: null

num_faces: [24576, 6144, 1536, 384, 96, 24]
#image_size: 32
#num_faces: [1024, 256, 64, 16]
#image_size: 64
#num_faces: [1536, 384, 96, 24]
num_eval_images: 256
num_vis_images: 256
num_vis_meshes: 64
batch_size: 4
views_per_sample: 2
random_views: False
num_workers: 16
optimize_lights: False
optimize_shininess: False

conv_aggregation: max
g_channel_max: 512
enc_conv: face

df_trunc: 0.3125
df_size: 0.0625
df_mean: 0.2839
df_std: 0.0686

shape_id: shape02344_rank02_pair183269
epoch_steps: 320

mbstd_on: 0

create_new_resume: False

wandb_main: False
suffix: ''

preload: False

prog_resume_ema: "/cluster_HDD/gondor/ysiddiqui/stylegan2-ada-3d-texture/runs/23020923_StyleGAN23D-CompCars_bigdtwin-clip_fg3bgg-lrd1g14-v8m8-1K_128/checkpoints/ema_000027474.pth"
prog_resume: "/cluster_HDD/gondor/ysiddiqui/stylegan2-ada-3d-texture/runs/23020923_StyleGAN23D-CompCars_bigdtwin-clip_fg3bgg-lrd1g14-v8m8-1K_128/checkpoints/_epoch=174.ckpt"

hydra:
  output_subdir: null # Disable saving of config files. We'll do that ourselves.
  run:
    dir: .