dataset_path: ../data/CADTextures/Photoshape/shapenet-chairs-manifold-highres-part_processed_color
mesh_path: ../data/CADTextures/Photoshape/shapenet-chairs-manifold-highres
pairmeta_path: ../data/CADTextures/Photoshape-model/metadata/pairs.json
df_path: ../data/CADTextures/Photoshape-model/shapenet-chairs-manifold
image_path: ../data/CADTextures/Photoshape/exemplars
mask_path: ../data/CADTextures/Photoshape/exemplars_mask
condition_path: ../data/CADTextures/Photoshape/shapenet-chairs-manifold_autoencoder
stat_path: ../data/CADTextures/Photoshape/shapenet-chairs-manifold-highres_stat.pt
uv_path: ../data/CADTextures/Photoshape/uv_map
silhoutte_path: ../data/CADTextures/Photoshape/uv_mask
normals_path: ../data/CADTextures/Photoshape/uv_normals
mesh_resolution: 64

experiment: test_run
seed: null
save_epoch: 100
sanity_steps: 1
max_epoch: 2000
scheduler: null
val_check_percent: 1.0
val_check_interval: 100
resume: null

num_mapping_layers: 5
lr_g: 0.002
lr_d: 0.001
lr_e: 0.0001
lazy_gradient_penalty_interval: 16
lazy_path_penalty_after: 0
lazy_path_penalty_interval: 4
latent_dim: 512
condition_dim: 512
lambda_gp: 1
lambda_plp: 2
lambda_patch: 1
ada_start_p: 0.  #to disable set to -1
ada_target: 0.6
ada_interval: 4
ada_fixed: False
g_channel_base: 32768
d_channel_base: 16384
d_channel_max: 512
features: normal
p_synthetic: 0.0
#normal
#position
#position+normal
#normal+laplacian
#normal+ff1+ff2
#normal+curvature
#normal+laplacian+ff1+ff2+curvature

random_bg: grayscale
colorspace: rgb

image_size: 512
render_size:
num_patch_per_view: 4
patch_size: 64
image_size_hres: 512
erode: True
camera_noise: 0.0
resume_ema: null

num_faces: [24576, 6144, 1536, 384, 96, 24]
#image_size: 32
#num_faces: [1024, 256, 64, 16]
#image_size: 64
#num_faces: [1536, 384, 96, 24]
num_eval_images: 256
num_vis_images: 256
num_vis_meshes: 64
batch_size: 4
views_per_sample: 2
random_views: False
num_workers: 8
optimize_lights: False
optimize_shininess: False

conv_aggregation: max
g_channel_max: 512
enc_conv: face

df_trunc: 0.3125
df_size: 0.0625
df_mean: 0.2839
df_std: 0.0686

shape_id: shape02344_rank02_pair183269
epoch_steps: 320

mbstd_on: 0

create_new_resume: False

wandb_main: False
suffix: ''

preload: False

hydra:
  output_subdir: null # Disable saving of config files. We'll do that ourselves.
  run:
    dir: .